### ISSUE TITLE
VIM使用

### ISSUE THREAD

**Issue by licoded** [licoded/self-study-drafts#27]
## fcitx输入法切换

> 实现效果: 普通模式关闭输入法, 插入模式自动恢复上次的输入法状态

### 设置

```vim
call plug#begin()
...
Plug 'lilydjwg/fcitx.vim'
...
call plug#end()

" 配置 lilydjwg/fcitx.vim
set ttimeoutlen=100
let g:fcitx5_remote = '/usr/bin/fcitx-remote'
```

### 遇到的问题

```
fcitx.vim not loaded: org.freedesktop.DBus.Error.ServiceUnknown: The name org.fcitx.Fcitx5 was not provided by any .service files
```

解决方法，按照 [GitHub README](https://github.com/lilydjwg/fcitx.vim) 里的，指定 `fcitx5-remote` 路径

### 参考链接

- https://github.com/lilydjwg/fcitx.vim
- https://blog.lilydjwg.me/2011/10/7/fcitx-vim-1-0-released.30049.html

**Comment by licoded** [comment]
### 快捷键-特殊

- `J` 合并本行和下一行(可以连续按，连续合并；也可以用`4J`)

**Comment by licoded** [comment]
## 背景及原因

不改键的情况下返回normal模式的几种方案:

1. ctrl + [ 需要两只手配合, 不够简练
2. ctrl + c 大概一年的时间都在使用, 但是语义是发送SIGINT, 少数情况下可能会导致意外的结果, 不完美
3. esc 直接使用距离太远

再看下面这个远古键盘(VIM诞生和流行时的键盘)

![8f28311a26dcccca7323237fea9e532c_1440w](https://user-images.githubusercontent.com/42663693/167984796-3c37e17e-777f-44d6-9cca-a91e334b1d43.jpeg)


## 实现效果

`Caps Lock` 点击是 `Esc`, 长按是 `Ctrl`

## 使用教程

1. 安装 `interception-dual-function-keys` 包
    
    ```bash
    yay -S interception-dual-function-keys
    ```
2. 创建 `/etc/interception/capslock2ctrlesc.yaml` 
    
    ```yaml
    TIMING:
        TAP_MILLISEC: 200 # 单击时长判定
        DOUBLE_TAP_MILLISEC: 150 # 可选配置
    
    MAPPINGS:
        - KEY: KEY_CAPSLOCK
          TAP: KEY_ESC
          HOLD: KEY_LEFTCTRL
    ```
3. 创建 `/etc/interception/udevmon.d/dual-function-keys.yaml` 
    
    ```yaml
    - JOB: "intercept -g $DEVNODE | dual-function-keys -c /etc/interception/capslock2ctrlesc.yaml | uinput -d $DEVNODE"
      DEVICE:
        NAME: "Lenovo Lenovo Wireless KB_Mouse KN100" # 任务作用的设备
    ```
    
    `NAME` 参数的设备名称通过这个命令确定 `sudo uinput -p -d /dev/input/by-id/X`, `X` 是路径下类似keyboard名称的设备, 如果这个路径下没有, 则需要在 `/dev/input` 目录下慢慢找了
5. `systemctl enable --now udevmon.service` 设置服务开机自启动，并立即启动

## 注意事项

我还做了如下软链接(但应该是不需要的)

```bash
sudo ln -s /etc/interception/udevmon.d/dual-function-keys.yaml /etc/interception/udevmon.yaml
```

```shell
lrwxrwxrwx 1 root root 51  5月 12 10:36 /etc/interception/udevmon.yaml -> /etc/interception/udevmon.d/dual-function-keys.yaml
```

## 参考链接

- [解放你的左手小指-最适合vim和程序员的改键方案](https://zhuanlan.zhihu.com/p/404819427)
- https://gitlab.com/interception/linux/plugins/dual-function-keys
